browser = chrome
gorest.base.url = https://gorest.co.in/
bearer.token = 7d5e83104f7522a466550038a08a96dac375299d1bb8389f18f09b821617d8c7
server = localhost
port = 5432
user = postgres
password = BeanProcessor